name: pipeline-env-ts-plugin
description: Plugin to create a github pipeline.
types:
- env
tags:
- environment
- typescript
- pipeline
inputs:
- label: "Runners label (e.g. my-github-runner, my-other-github-runner):"
  type: text
  name: runners_label

- label: "Custom IAM Permissions?"
  type: boolean
  name: custom_iam

- label: "Custom Policy (e.g. StacksPotContainerPolicy):"
  type: text
  name: custom_policy
  condition:
      variable: "custom_iam"
      operator: "=="
      value: true
